version: "1.0"
services:
  db:
    image: postgres:15
    container_name: postgres_auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authdb
    ports:
      - "5434:5432"
    volumes:
      - fastapi_auth_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d authdb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: fastapi_auth
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      POSTGRES_URL: postgresql+asyncpg://postgres:postgres@db:5432/authdb
      SECRET_KEY: SUPERSECRET123

volumes:
  fastapi_auth_pgdata:
